### ISSUE TITLE
Inconsistent combining rule with your previous published papers

### ISSUE THREAD

**Issue by XiaoboLinlin** [agiliopadua/ilff#14]
Dear Padua group,

In the two papers of yours as shown below, your group is using Lorentz-Berthelot as mixing rule, but in your topology file like ff.itp, you are using Geometric mixing rule. Could you let me know which mixing rule I should use? Thank you so much in advance.

doi:10.1007/s00214-012-1129-7.  
10.1021/jp0362133

Best,
Xiaobo

**Comment by agiliopadua** [comment]
We've been using geometric combining rules for the sigma parameters for many years. Only in some very earlier publications we used arithmetic. What is written in the 2012 review is a mistake (sorry).
I prefer geometric combining rules for sigma when doing free energy calculations, since when the diameter of a site goes to zero, those corresponding to the unlike interactions also go to zero.
In most cases geometric or arithmetic for sigmas will give very close results for thermodynamic or transport properties.
Kind regards,
Agilio

**Comment by XiaoboLinlin** [comment]
> We've been using geometric combining rules for the sigma parameters for many years. Only in some very earlier publications we used arithmetic. What is written in the 2012 review is a mistake (sorry).
> I prefer geometric combining rules for sigma when doing free energy calculations, since when the diameter of a site goes to zero, those corresponding to the unlike interactions also go to zero.
> In most cases geometric or arithmetic for sigmas will give very close results for thermodynamic or transport properties.
> Kind regards,
> Agilio

Hi Agilio,
Thank you so much for your clarification! Much appreciate it. That makes sense.
Best,
Xiaobo
