### ISSUE TITLE
energy units from il.ff to lammps data

### ISSUE THREAD

**Issue by guhaohao0991** [agiliopadua/ilff#15]
The source code about force field on your GitHub use kj/mol for energy, and with “fftool.py” you provide can transform to LAMMPS data format conveniently but with different units, kcal/mol (for units real).  The ratio I thought was 1 kcal/mol = 4.184 kj/mol. But the result seems to be 2 * 4.184 kj/mol for bonds coefficients.

**Comment by guhaohao0991** [comment]
Thank you for your patience and kind cooperation, I am eagerly looking forward to hearing from you.

**Comment by mattwthompson** [comment]
This is probably because LAMMPS does not use the 1/2 coefficient that most other engines do:


* https://docs.lammps.org/bond_harmonic.html
* Equation 2.2 in https://www.ccp5.ac.uk/sites/www.ccp5.ac.uk/files/dl_poly_classic/USRMAN.pdf
* https://manual.gromacs.org/2021/reference-manual/functions/bonded-interactions.html#equation-eqnharmbondstretch

**Comment by agiliopadua** [comment]
The factor 2 is because some write harmonic potentials as k/2 * (x - x0)^2 whereas others use K * (x - x0)^2.
The literature on force fields often uses the latter (and lammps adopted this notation), whereas in fftool I preferred the former.

**Comment by guhaohao0991** [comment]
Thanks a lot for your patience and kindness!

Sent from Mail for Windows
